### ISSUE TITLE
Inkscape: Fontconfig error

### ISSUE THREAD

**Issue by shoeffner** [Homebrew/homebrew-gui#30]
I ran into the exact same problem as https://github.com/Homebrew/homebrew-x11/issues/168 , and was also able to solve it as described there by reinstalling fontconfig from source:

```
brew reinstall --build-from-source fontconfig
```

Is it possible to add this as a default step while installing inkscape?

**Comment by MikeMcQuaid** [comment]
This has been moved to Homebrew Cask.
