### ISSUE TITLE
Move HexChat to quartz GTK

### ISSUE THREAD

**Issue by hameerabbasi** [Homebrew/homebrew-gui#42]
Moving HexChat to gtk-quartz will be a huge boost for it, especially for the performance issues such as the huge input lag you get after pressing enter when sending a message.

**Comment by MikeMcQuaid** [comment]
This has been moved to Homebrew Cask.

**Comment by TingPing** [comment]
@MikeMcQuaid The HexChat Cask will not be receiving any official releases any more so it should remain here.

**Comment by MikeMcQuaid** [comment]
@TingPing Sorry, we're migrating everything to Homebrew Cask.
