### ISSUE TITLE
[meld] Cannot import: GTK+

### ISSUE THREAD

**Issue by muammar** [Homebrew/homebrew-gui#5]
I have installed meld as shown below:

```
brew -v install homebrew/gui/meld
```

When the application is launched it fails importing `GTK+` and `gi`.

```
 ✘ muammar@zarathustra ⮀ ~ ⮀ meld
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bindtextdomain'
Cannot import: GTK+
No module named gi
```

I install `gi`:

```
pip2.7 install gi
```

However the problem with `GTK+` is still there. 

```
 muammar@zarathustra ⮀ ~ ⮀ meld
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bindtextdomain'
Cannot import: GTK+
No module named repository
```

Nothing seems missing though:

```
 ✘ muammar@zarathustra ⮀ ~ ⮀ brew missing
 muammar@zarathustra ⮀ ~ ⮀
```

How can I solve this problem?

Thanks.

**Comment by tschoonj** [comment]
Works fine here though.

I think you made a bit of a mess of your installation by mixing Homebrew and pip packages. There's no need to install `gi` by pip as it is provided by `pygobject3`, which is a dependency of `meld`.

What does `brew doctor` say?

**Comment by muammar** [comment]
@tschoonj I reinstalled `pygobject3`, and now it works. I also uninstalled `gi`. It is strange, because when I submitted this report I had reinstalled all `meld` dependencies. Sorry for the noise. I will proceed to close this report. Thanks.
