### ISSUE TITLE
Faulty build of latest Inkscape v0.92

### ISSUE THREAD

**Issue by emilkaae** [Homebrew/homebrew-gui#50]
Hi,

I am unsure who maintains the Inkscape formula, so forgive me if I am asking in the wrong forum. I have experienced issues with the build on OS X 10.11.6 when installing Inkscape via homebrew: it appears the "trace bitmap" function does not work; perhaps because the potrace dependency is not correctly set up.

Any idea how to repair that?

Best regards,
Emil

**Comment by MikeMcQuaid** [comment]
This has been moved to Homebrew Cask.

**Comment by tghs** [comment]
@emilkaae I've applied the fix you mentioned in the new home for this formula: https://github.com/caskformula/homebrew-caskformula

```bash
brew install caskformula/caskformula/inkscape
```
