### ISSUE TITLE
inkscape gone - back to 0.91

### ISSUE THREAD

**Issue by baikal** [Homebrew/homebrew-gui#53]
I recently installed inkscape 0.92 from this tap. Worked fine.

Did a 'brew update' just some minutes ago, this did 'brew uninstall --force inkscape' without asking and installed (from cask) inkscape 0.91. I can see some points in going to cask - but deleting files from my computer without even prompting is not ok at all !

Seriously, I had a working Inkscape 0.92 (thanks to your work and providing an brew) - and now im am left without, and (for the time being) without a way to get it.

=====
$ brew update
Updated Homebrew from c9d7bab6ca to 6f305ad3dc.
Updated 7 taps (caskroom/cask, dholm/sdr, homebrew/core, homebrew/gui, homebrew/science, homebrew/x11, pothosware/pothos).
==> New Formulae
dholm/sdr/rtl433                         todoman
homebrew/science/dl_poly_classic
==> Updated Formulae
crystal-lang                             opus
dar                                      parallel ✔
docker                                   pothosware/pothos/limesuite
docker-swarm                             qemu ✔
extract_url                              svtplay-dl
gdb                                      swift
git-tracker                              swiftformat
gitlab-ci-multi-runner                   swiftlint
homebrew/science/cantera                 unrar ✔
homebrew/science/dealii                  vim
homebrew/science/oce                     yle-dl
lean-cli                                 youtube-dl ✔
libvirt                                  zimg
==> Deleted Formulae
homebrew/gui/gtkwave                     homebrew/gui/meld ✔
homebrew/gui/hexchat                     homebrew/gui/transmission-remote-gtk
homebrew/gui/inkscape ✔
==> inkscape has been moved to Homebrew-Cask.
==> brew uninstall --force inkscape
Uninstalling inkscape... (1,015 files, 124.0M)
==> brew prune
Pruned 5 symbolic links and 28 directories from /usr/local
Unlinked 5 apps from /Users/marcel/Applications
==> brew cask install inkscape
==> Satisfying dependencies
complete
==> Downloading https://inkscape.global.ssl.fastly.net/media/resources/file/Inks
######################################################################## 100,0%
==> Verifying checksum for Cask inkscape
==> Moving App 'Inkscape.app' to '/Applications/Inkscape.app'
==> Symlinking Binary 'inkscape' to '/usr/local/bin/inkscape'
🍺  inkscape was successfully installed!

**Comment by ilovezfs** [comment]
Sorry for the downgrade. I suggest opening a pull request to https://github.com/caskroom/homebrew-cask/blob/master/Casks/inkscape.rb with the newer version if you'd like to help remedy the situation.

**Comment by baikal** [comment]
Sorry about the double-post.
There is no point in opening a pull request to Casks/inkscape.rb, as the Inkscape project does not (not yet?) provide binaries for 0.92/osx - maybe because of library dependencies, don't know. Which forces one to MacPorts, although I do prefer Homebrew. Yes, I know I can grab the Formula from two days ago and just shove it somewhere or make a new Tap from it or plain simply recover the Cellar section from my backup.
Anyway, my main concern (not specifically about inkscape) is about 'brew update'. Doing anything on installed packages (like removing, no questions asked) does not seem to be right at all - according to the documentation it is supposed to update the "metadata" of package-build-and-dependency-information. And then 'upgrade', 'install', 'uninstall' and the like would do things on the Cellar. And that is why I asked the other question, if really 'brew update' is supposed to remove things according to tap-migrations.json ?

**Comment by MikeMcQuaid** [comment]
> And that is why I asked the other question, if really 'brew update' is supposed to remove things according to tap-migrations.json ?

Yes, it is.

**Comment by tghs** [comment]
Given the current situation, I propose resurrecting the Inkscape formula from here in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/9355

**Comment by tghs** [comment]
It's not going to go into homebrew-core, so I've set up a tap for providing formulae for software packaged as casks. To install Inkscape:

```bash
brew install caskformula/caskformula/inkscape
```
