### ISSUE TITLE
Hexchat

### ISSUE THREAD

**Issue by Mirppc** [Homebrew/homebrew-gui#55]
The hexchat documentation is written to use the /homebrew/homebrew-gui/ depreciated repository.  This is an issue as the version of hexchat in the cask repo is depreciated and one cannot install hexchat with the --HEAD command from CASK.  the 2.10 version in the CASK repo has broken scripting including but not limited to the sysinfo command.  The Cask version also has issues connecting to any server.

http://hexchat.readthedocs.io/en/latest/building.html#homebrew

**Comment by MikeMcQuaid** [comment]
This repository is deprecated, sorry.
